contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5053546
    [1] => 24931450
    [2] => D
    [3] => 1
    [4] => PATIENT WAS REVISED TO ADDRESS PAIN.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5053891
    [1] => 24942297
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED SUCTION LOSS OCCURRED DURING PROCEDURE WHILE LASER FIRING WITH AN INTRALASE PATIENT INTERFACE (PI). THERE IS NO PATIENT INJURY REPORTED AND THE CASE WAS COMPLETED WITH THE SAME PI. IT WAS REPORTED THAT TWO (2) PROCEDURES WERE LOST. THE INITIAL PROCEDURE WAS LOST PRIOR TO LASER FIRING DUE TO AN ISSUE NOT RELATED TO ANY AMO PRODUCTS. THE SECOND PROCEDURE WAS LOST WHILE LASER FIRING AND IS THE SUBJECT COMPLAINT FOR THIS REPORT.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5054264
    [1] => 24959614
    [2] => D
    [3] => 1
    [4] => AN OPTOMETRIST REPORTED THAT TEN DAYS FOLLOWING BILATERAL LASIK, THE PATIENT PRESENTED WITH A TRANSIENT LIGHT SENSITIVITY (TLS) IN BOTH EYES. THE PATIENT REPORTED BURNING SENSATION AND LIGHT SENSITIVITY FOR TWO DAYS. THE PATIENT WORE SUNGLASSES INDOORS ESPECIALLY WHILE WORKING AT THE COMPUTER. THE PATIENT WAS TREATED WITH INCREASED TOPICAL STEROID DROPS. ADDITIONAL INFORMATION HAS BEEN REQUESTED. THERE ARE TWO RELATED REPORTS FOR THIS PATIENT. THIS REPORT ADDRESSES THE PATIENT'S RIGHT EYE, AND ANOTHER MANUFACTURER REPORT WILL BE FILED FOR THE FELLOW EYE.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5054273
    [1] => 24986419
    [2] => D
    [3] => 1
    [4] => AN OPTOMETRIST REPORTED THAT TEN DAYS FOLLOWING BILATERAL LASIK, THE PATIENT PRESENTED WITH A TRANSIENT LIGHT SENSITIVITY (TLS) IN BOTH EYES. THE PATIENT REPORTED BURNING SENSATION AND LIGHT SENSITIVITY FOR TWO DAYS. THE PATIENT WORE SUNGLASSES INDOORS ESPECIALLY WHILE WORKING AT THE COMPUTER. THE PATIENT WAS TREATED WITH INCREASED TOPICAL STEROID DROPS. ADDITIONAL INFORMATION HAS BEEN REQUESTED. THERE ARE TWO RELATED REPORTS FOR THIS PATIENT. THIS REPORT ADDRESSES THE PATIENT'S LEFT EYE, AND ANOTHER MANUFACTURER REPORT WILL BE FILED FOR THE FELLOW EYE.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5054964
    [1] => 24985146
    [2] => D
    [3] => 1
    [4] => CENTER DIRECTOR REPORTED ECTASIA IN A PATIENT'S RIGHT EYE 5 YEARS AND 20 DAYS POST LASIK. TOPOGRAPHY WAS REPORTED TO HAVE BEEN SUSPICIOUS. PATIENT REPORTED THAT VISION HAD BEEN UNCLEAR FOR SIX MONTHS. REPORTER INFORMED THAT ANOTHER PHYSICIAN HAS BEEN CONSULTED ON THE ISSUE. ADDITIONAL INFORMATION HAS BEEN REQUESTED. THERE ARE TWO RELATED REPORTS FOR THIS PATIENT. THIS REPORT ADDRESSES THE PATIENT'S RIGHT EYE, AND ANOTHER MANUFACTURER REPORT WILL BE FILED FOR THE FELLOW EYE.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5055020
    [1] => 24981230
    [2] => D
    [3] => 1
    [4] => AN OPTOMETRIST REPORTED STAGE 1 DIFFUSE LAMELLAR KERATITIS (DLK) AND CORNEAL HAZE IN A PATIENT'S LEFT EYE ONE DAY POST LASIK. PATIENT REPORTED DRY EYES. PATIENT RINSED EYES OUT WITH WATER. TOPICAL STEROID DOSAGE WAS INCREASED. UPON FOLLOW UP, ALL ISSUES WERE REPORTED TO BE RESOLVED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5055084
    [1] => 24985318
    [2] => D
    [3] => 1
    [4] => CENTER DIRECTOR REPORTED ECTASIA IN A PATIENT'S LEFT EYE 5 YEARS AND 20 DAYS POST LASIK. TOPOGRAPHY WAS REPORTED TO HAVE BEEN SUSPICIOUS. PATIENT REPORTED THAT VISION HAD BEEN UNCLEAR FOR SIX MONTHS. REPORTER INFORMED THAT ANOTHER PHYSICIAN HAS BEEN CONSULTED ON THE ISSUE. ADDITIONAL INFORMATION HAS BEEN REQUESTED. THERE ARE TWO RELATED REPORTS FOR THIS PATIENT. THIS REPORT ADDRESSES THE PATIENT'S LEFT EYE, AND ANOTHER MANUFACTURER REPORT WILL BE FILED FOR THE FELLOW EYE.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5055415
    [1] => 24983016
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED SUCTION LOSS OCCURRED DURING PROCEDURE WHILE LASER FIRING WITH AN INTRALASE PATIENT INTERFACE (PI). NO PATIENT INJURY AND/OR COMPLICATIONS WERE REPORTED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5055875
    [1] => 24992120
    [2] => D
    [3] => 1
    [4] => A SURGEON REPORTED A DECENTERED ABLATION WHICH LEAD TO AN UNEXPECTED OUTCOME IN A PATIENT'S EYE. UPON FOLLOW UP, COPIES OF THE PATIENT'S TOPOGRAPHIES WERE SENT TO A DOCTOR FOR REVIEW WHO STATED THAT THE ABLATION WAS DECENTERED. SITE FOUND OUT THIS INFORMATION 2 WEEKS AFTER THE PROCEDURE. PATIENT IS CURRENTLY WEARING A TORIC CONTACT LENS. PATIENT REPORTS DISTORTIONS AND HALOS. PATIENT IS SCHEDULED TO SEE ANOTHER PHYSICIAN.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5058298
    [1] => 25114317
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED THEY EXPERIENCED SUCTION LOSS DURING SURGERY WITH AN INTRALASE PATIENT INTERFACE (PI) AFTER THE PATIENT WAS APPLANATED AND AFTER THE LASER FIRED. IT IS ALSO NOTED THAT THE PROCEDURE WAS COMPLETED SUCCESSFULLY. THERE WAS NO PATIENT INJURY REPORTED AND NO SURGICAL INTERVENTION WAS REQUIRED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5058459
    [1] => 25098449
    [2] => D
    [3] => 1
    [4] => THE CLINIC REPORTED THAT A FLAP WAS DIFFICULT TO LIFT AND TREATMENT WAS ABORTED FOR THE RIGHT EYE. THERE WAS NO SUCTION LOSS DURING THE FLAP CREATION HOWEVER SURGEON CLAIMS THE FLAP WAS NOT FULLY CUT. IT WAS STATED THAT THE PATIENT HAD NO LOSS OF BEST CORRECTED VISUAL ACUITY (BCVA). THE PATIENT HAD NO COMPLAINTS. PATIENT REPORTED SYMPTOMS ARE NOT INTERFERING WITH DAILY ACTIVITIES. PATIENT WAS CONVERTED TO PHOTOREFRACTIVE KERATECTOMY NEXT DAY. LEFT EYE HAD NO ISSUES WITH FLAP AND SURGEON DECIDED TO POSTPONE UNTIL NEXT DAY. BCVA FROM (B)(6) 2015: RIGHT EYE PRE-OP 20/15 -1.75 X -3.25 X 179; LEFT EYE PRE-OP 20/20 -1.50 X -2.50 X 4.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5058465
    [1] => 25099064
    [2] => D
    [3] => 1
    [4] => THE CLINIC REPORTED THAT A EYELASH INTERFERED WITH FLAP CUTTING IN RIGHT EYE AND HE WAS UNABLE TO LIFT THE FLAP AS A SEGMENT OF IT WAS NOT FULLY CUT. PATIENT WAS CONVERTED TO PHOTOREFRACTIVE KERATECTOMY NEXT TREATMENT DAY. IT WAS STATED THAT THE PATIENT HAD NO LOSS OF BEST CORRECTED VISUAL ACUITY (BCVA). THE PATIENT HAD NO COMPLAINTS. PATIENT REPORTED SYMPTOMS ARE NOT INTERFERING WITH DAILY ACTIVITIES. SURGEON CONTINUE WITH LEFT EYE WITH NO ISSUES AND DECIDED TO DO EXCIMER NEXT TREATMENT DAY. BCVA FROM (B)(6) 2015; RIGHT EYE PRE-OP 20/20 -.50 X -.50 X 165; LEFT EYE PRE-OP 20/20 -.75 X -.50 X 18.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5059031
    [1] => 25097652
    [2] => D
    [3] => 1
    [4] => THE CLINIC REPORTED THAT A LASER VISION CORRECTION PATIENT PRESENTED WITH TRANSIENT LIGHT SENSITIVITY IN BOTH EYES AT THE 1 WEEK POST TREATMENT VISIT. THE TOPICAL STEROID DOSAGE WAS INCREASED. IT WAS STATED THAT THE PATIENT HAD NO LOSS OF BEST CORRECTED VISUAL ACUITY (BCVA). THE PATIENT COMPLAINED OF LIGHT SENSITIVITY. PATIENT REPORTED SYMPTOMS ARE NOT INTERFERING WITH DAILY ACTIVITIES. BCVA FROM (B)(6) 2015: RIGHT EYE PRE-OP 20/20 -1.00 X -.75 X 110; LEFT EYE PRE-OP 20/20 -1.25 X -.75X 85.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5059033
    [1] => 25110996
    [2] => D
    [3] => 1
    [4] => THE SURGERY CENTER REPORTED LOST SUCTION WITH THE PATIENT INTERFACE (PI) ON A LASER TREATMENT AFTER LASER STARTED. THERE IS NO PATIENT INJURY REPORTED AND THE CASE WAS COMPLETED WITH NEW PI WITHOUT FURTHER COMPLICATIONS.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5059034
    [1] => 25111067
    [2] => D
    [3] => 1
    [4] => THE SURGERY CENTER REPORTED LOST SUCTION WITH THE PATIENT INTERFACE (PI) ON A LASER TREATMENT AFTER LASER STARTED. THERE IS NO PATIENT INJURY REPORTED AND THE CASE WAS COMPLETED WITH NEW PI WITHOUT FURTHER COMPLICATIONS.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5059740
    [1] => 25104888
    [2] => D
    [3] => 1
    [4] => AN OPTOMETRIST REPORTED A BILATERAL CASE OF CORNEAL HAZE, OBSERVED AT NINE WEEKS POST PHOTO REFRACTIVE KERATECTOMY (PRK) TREATMENT. REPORTER INDICATED TOPICAL STEROID EYE DROP DOSAGE WAS INCREASED. ADDITIONAL INFORMATION HAS BEEN REQUESTED THERE ARE TWO RELATED REPORTS FOR THIS PATIENT. THIS REPORT ADDRESSES THE PATIENT'S RIGHT EYE, AND ANOTHER MANUFACTURER REPORT WILL BE FILED FOR THE FELLOW EYE.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5059799
    [1] => 25099136
    [2] => D
    [3] => 1
    [4] => SURGEON REPORTED THAT PATIENT PRESENTED WITH DIFFUSE LAMELLAR KERATITIS (DLK) STAGE III IN BOTH EYES POST TREATMENT. THE SURGEON SAID THE EVENT OCCURRED ABOUT 2-3 MONTHS AGO AND HE WASN'T SURE OF THE EXACT DATES OR THE PATIENT'S DETAILS. PATIENT'S DLK RESOLVED AND POST OP BEST CORRECTED VISUAL ACUITY WAS 20/25 IN BOTH EYES. HE ALSO MENTIONED A NEW TECHNICIAN HAS BEEN IN THE SURGICAL ROOM OVER THE PAST FEW MONTHS.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5059802
    [1] => 25097643
    [2] => D
    [3] => 1
    [4] => THE CLINIC REPORTED THAT A LASER VISION CORRECTION PATIENT PRESENTED TO BE EVALUATED FOR BLURRED VISION IN BOTH EYES 3 YEARS POST TREATMENT. PATIENT WAS DIAGNOSED WITH ECTASIA AND SURGEON DISCUSSED ENHANCEMENT OPTIONS. IT WAS STATED THAT THE PATIENT HAD NO LOSS OF BEST CORRECTED VISUAL ACUITY (BCVA). THE PATIENT COMPLAINED OF SLIGHTLY BLURRED VISION. PATIENT REPORTED SYMPTOMS ARE NOT INTERFERING WITH DAILY ACTIVITIES. BCVA FROM (B)(6) 2012: RIGHT EYE PRE-OP 20/25 -12.50 X -.75 X 35, LEFT EYE PRE-OP 20/20 -12.75 X -.75 X 175. BCVA FROM (B)(6) 2012: RIGHT EYE POST-OP 20/20 -.50 X .00 X 90, LEFT EYE POST-OP 20/20 -.25 X .00 X 90.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5061067
    [1] => 25168569
    [2] => D
    [3] => 1
    [4] => THE CLINIC REPORTED THAT DURING SLIT LAMP EXAM A LASER VISION CORRECTION PATIENT PRESENTED WITH SUB/INTRAEPITHELIAL CYSTS IN LEFT EYE MORE THAN 2 MONTHS POST TREATMENT. IT WAS STATED THAT THE PATIENT HAD LOSS OF BEST CORRECTED VISUAL ACUITY (BCVA). THE PATIENT COMPLAINED OF BLURRED VISION IN LEFT EYE. PATIENT REPORTED SYMPTOMS ARE NOT INTERFERING WITH DAILY ACTIVITIES. BCVA FROM (B)(6) 2014: RIGHT EYE PRE-OP 20/20 -4.50 X .00 X 90; LEFT EYE PRE-OP 20/20 -4.75 X -.50 X 125. BCVA FROM (B)(6) 2015: RIGHT EYE POST-OP 20/20 1.00 X -.50 X 29; LEFT EYE POST-OP 20/40 1.00 X -1.50 X 83. ACCOUNT REPORTED THAT SECONDARY SURGICAL INTERVENTION WAS REQUIRED AS EPI SCRAPE AND POSSIBLE LIFT AND RINSE WILL BE PERFORMED TO RESOLVE THE ISSUE.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5061099
    [1] => 25168629
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED THAT THEY EXPERIENCED LACK OF SUCTION (PRIOR TO LASER  FIRING) WITH AN INTRALASE PATIENT INTERFACE (PI). IT WAS REPORTED THAT PATIENT WAS CONVERTED TO PHOTOREFRACTIVE KERATECTOMY. THE PROCEDURE WAS COMPLETED SUCCESSFULLY.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5061211
    [1] => 25169979
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED THAT THEY EXPERIENCED LACK OF SUCTION (PRIOR TO LASER FIRING) WITH AN INTRALASE PATIENT INTERFACE (PI). IT WAS REPORTED THAT PATIENT WAS CONVERTED TO PHOTOREFRACTIVE KERATECTOMY. THE PROCEDURE WAS COMPLETED SUCCESSFULLY.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5061586
    [1] => 25180291
    [2] => D
    [3] => 1
    [4] => IT WAS REPORTED THAT SURGEON REQUESTED A TWO SURFACE PHOTOTHERAPEUTIC KERATECTOMY (PTK) TREATMENT TO BE PROGRAM FOR THE LEFT EYE (ONE FOR THE PERIPHERAL CORNEA AND ONE FOR THE CENTRAL CORNEA) AND THE TREATMENTS WERE SWITCHED (THE ONE INTENDED FOR THE CORNEA WAS GIVEN TO THE PERIPHERAL AREA AND VICEVERSA). REQUESTED INFORMATION TO THE ACCOUNT AND RECEIVED THE FOLLOWING DATA. PATIENT PRE OP BEST CORRECTED VISUAL ACUITY (BCVA) IS 20/50 AND THERE WAS NO CHANGE FOR POST OP BCVA. IT WAS REPORTED THAT SURGEON WILL LET THE EYE REST FOR A FEW MONTHS BEFORE RETREATING.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5062134
    [1] => 25214071
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED SUCTION LOSS OCCURRED DURING PROCEDURE WHILE LASER FIRING WITH AN INTRALASE PATIENT INTERFACE (PI). NO PATIENT INJURY AND/OR COMPLICATIONS WERE REPORTED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5062146
    [1] => 25213498
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED SUCTION LOSS OCCURRED DURING PROCEDURE WHILE LASER FIRING WITH AN INTRALASE PATIENT INTERFACE (PI). NO PATIENT INJURY AND/OR COMPLICATIONS WERE REPORTED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5062187
    [1] => 25207841
    [2] => D
    [3] => 1
    [4] => ACCOUNT REPORTED THAT SURGEON CREATED A FLAP WITHOUT ISSUES BUT DURING LIFTING THE SURGEON TORE THE FLAP. THERE WAS NO DIFFICULT LIFT. THE SURGEON DECIDED TO ABORT EXCIMER TREATMENT AND USED A BANDAGE CONTACT LENS. NO BEST CORRECTED VISUAL ACUITY (BCVA) TO REPORT. SURGEON IS GOING TO WAIT TO ALLOW HEALING TO DECIDE WHAT TREATMENT WILL FOLLOW.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5062982
    [1] => 25208116
    [2] => D
    [3] => 1
    [4] => THE CLINIC REPORTED THAT A LASER VISION CORRECTION PATIENT PRESENTED WITH SMALL LINT FIBER UNDER RIGHT EYE EDGE OF THE FLAP ONE (1) DAY POST TREATMENT. IT WAS STATED THAT THE PATIENT HAD NO LOSS OF BEST CORRECTED VISUAL ACUITY (BCVA). THE PATIENT HAD NO COMPLAINTS. PATIENT REPORTED SYMPTOMS ARE NOT INTERFERING WITH DAILY ACTIVITIES. IT WAS REPORTED THAT SECONDARY SURGICAL INTERVENTION WAS REQUIRED TO REMOVED THE FOREIGN BODY. BCVA FROM (B)(6) 2015: RIGHT EYE PRE-OP 20/20 -3.25 X -.75 X 155; LEFT EYE PRE-OP 20/20 -3.00 X -.75 X 25.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5062992
    [1] => 25208319
    [2] => D
    [3] => 1
    [4] => CLINIC REPORTED LASER VISION CORRECTION PATIENT PRESENTED TO BE EVALUATED FOR ENHANCEMENT IN BOTH EYES 5 YEARS POST TREATMENT. PATIENT WAS DIAGNOSED WITH ECTASIA AS ORBSCANS WERE SUSPICIOUS AND WERE SENT FOR REVIEW. IT WAS STATED THAT THE PATIENT HAD LOSS OF BEST CORRECTED VISUAL ACUITY (BCVA). THE PATIENT COMPLAINED OF UNCLEAR VISION FOR THE LAST 6 MONTHS. PATIENT REPORTED SYMPTOMS ARE NOT INTERFERING WITH DAILY ACTIVITIES. BCVA FROM (B)(6) 2010: RIGHT EYE PRE-OP 20/15 -1.25 X -2.50 X 5; LEFT EYE PRE-OP 20/15 -1.50 X -3.75 X 172. BCVA FROM (B)(6) 2010: RIGHT EYE POST-OP 20/15 .00 X -.25 X 48; LEFT EYE POST-OP 20/15 0.00 X 0.00 X 0. BCVA FROM (B)(6) 2015: RIGHT EYE POST-OP 20/40; LEFT EYE POST-OP 20/20.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5063000
    [1] => 25208483
    [2] => D
    [3] => 1
    [4] => THE CLINIC REPORTED THAT A LASER VISION CORRECTION PATIENT PRESENTED WITH DIFFUSE LAMELLAR KERATITIS (DLK) STAGE I AND HAZE IN LEFT EYE 1 DAY POST TREATMENT. TOPICAL STEROID DOSAGE WAS INCREASED. IT WAS STATED THAT THE PATIENT HAD NO LOSS OF BEST CORRECTED VISUAL ACUITY (BCVA). THE PATIENT COMPLAINED OF DRY EYES AND RINSED EYES WITH WATER FOR RELIEF OF DRYNESS. PATIENT REPORTED SYMPTOMS ARE NOT INTERFERING WITH DAILY ACTIVITIES. BCVA FROM (B)(6) 2015: RIGHT EYE PRE-OP 20/20 -4.50 X -.50 X 161; LEFT EYE PRE-OP 20/20 -5.50 X -.25 X 145.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5063133
    [1] => 25215817
    [2] => D
    [3] => 1
    [4] => CUSTOMER REPORTED PATIENT HAD ANTERIOR CAPSULE TEAR. NO PATIENT DETAILS OR ADDITIONAL INFORMATION WAS PROVIDED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5063137
    [1] => 25209876
    [2] => D
    [3] => 1
    [4] => CUSTOMER REPORTED PATIENT HAD ANTERIOR CAPSULE TEAR. NO PATIENT DETAILS OR ADDITIONAL INFORMATION WAS PROVIDED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5063140
    [1] => 25208574
    [2] => D
    [3] => 1
    [4] => ACCOUNT REPORTED THAT THERE WAS A BUTTONHOLE THROUGH RIGHT EYE FLAP THAT WAS INDUCED BY SURGEON AND PATIENT. PATIENT MOVED ABRUPTLY AND SURGEON POKED THROUGH THE FLAP WITH HIS SEIBEL. FLAPS WERE CREATED JUST FINE WITH INTRALASE. EXCIMER LASER PORTION ABORTED AFTER BOTH FLAPS WERE CREATED. A BANDAGE CONTACT LENS WAS APPLIED. AT 1 DAY POST OP 20/70 DUE TO INTRALASE INFLAMMATION. PATIENT TO RETURN IN 3 MONTHS FOR PHOTOREFRACTIVE KERATECTOMY IN BOTH EYES.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5063145
    [1] => 25208830
    [2] => D
    [3] => 1
    [4] => CUSTOMER REPORTED PATIENT HAD ANTERIOR CAPSULE TEAR. NO PATIENT DETAILS OR ADDITIONAL INFORMATION WAS PROVIDED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5063244
    [1] => 25931202
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED THEY EXPERIENCED SUCTION LOSS DURING SURGERY WITH AN INTRALASE PATIENT INTERFACE (PI) AFTER THE PATIENT WAS APPLANATED AND AFTER THE LASER FIRED. IT WAS REPORTED THAT THE PROCEDURE WAS COMPLETED SUCCESSFULLY BY USING NEW PI AND SECOND LASER FIRING. THERE WAS NO PATIENT INJURY REPORTED AND NO SURGICAL INTERVENTION WAS REQUIRED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5064090
    [1] => 25353960
    [2] => D
    [3] => 1
    [4] => HAD LASIK IN A HIGH VOLUME CENTER ON (B)(6) 2015. DID NOT SEE A DOCTOR BEFORE THE OPERATING DAY. I HAD ALREADY PAID AND SIGNED THE CONSENT FORM, WHICH WAS GIVEN TO ME TO READ IN THE WAITING HALL AFTER TELLING ME THAT ALL SIDE EFFECTS ARE RARE. THE DOCTOR BRIEFLY TOLD ME I HAD LARGER THAN USUAL PUPILS (BOTH 7.8 MM) BUT WAVEFRONT GUIDED LASIK WAS A GOOD TECHNOLOGY FOR THIS, AND DID NOT TELL ME ABOUT WHAT COMPLICATIONS I MAY HAVE. NO EXPLANATION REGARDING RISKS RELATED TO FLAP, ESPECIALLY SINCE I'M VERY ACTIVE AND PARTICIPATE IN MANY SPORTS. ON (B)(6) 2015, HAD A TRAUMATIC FLAP DISLOCATION ON RIGHT EYE WHILE PLAYING BASKETBALL. FLAP WAS RELIFTED, IRRIGATED AND REPLACED TWICE THE DAY AFTER. PERSISTENT, SIGNIFICANT MACROSTRIAE ON VISUAL AXIS REQUIRED REINTERVENTION. ON (B)(6) 2015, I HAD 5 TEMPORARY PERIPHERAL SUTURES PLACED ON CORNEA TO ELIMINATE THE STRIAE. I HAVE SEVERE DRY EYES (RIGHT WAS WORSE THAN LEFT). I'VE STARTED USING THE EXPENSIVE DRUG RESTASIS. I HAVE A LOT OF SUBJECTIVE VISUAL ABERRATIONS, WORSE BY NIGHT BUT PRESENT BY DAY. CORNEAL SCANS SHOW MILD-MODERATE COMA AND SPHERICAL ABERRATION, ACCORDING TO MY OPHTHALMOLOGIST. MY VISION CANNOT BE CORRECTED TO 20/15 AS BEFORE SURGERY BUT 20/20. VISION QUALITY IS BAD, WITH SUBJECTIVE LOSS OF CONTRAST, MULTIPLIED IN LOW LIGHT. I HAVE PAIN IN RIGHT EYE WHICH MAY VERY WELL BE OF NEUROPATHIC ETIOLOGY. THIS IS THE MOST DISABLING SYMPTOM. I AM ON DISABILITY LEAVE FROM WORK FOR TWO MONTHS, WITH ADAPTATION DISORDER WITH ANXIOUS AND DEPRESSIVE MOOD. I HAVE HAD SUICIDAL THOUGHTS. I DON'T HAVE ANY PSYCHOLOGICAL OR MEDICAL PAST MEDICAL HISTORY PRIOR TO THIS. I AM A (B)(6) MEDICAL RESIDENT IN HIS 2ND YEAR OF INTERNAL MEDICINE AND I WONDER HOW THE FDA ACCEPTS THAT EVEN ONE CASE LIKE MINE HAPPENS. THIS IS AN ELECTIVE SURGERY AND I WISH A SERIOUS ADMINISTRATION OVERSAW THIS BUSINESS WHO HAS RUINED MY LIFE. HOW MANY RUINED LIVES FOR SOME SUPPOSEDLY HAPPY PATIENTS? I WAS TOLD TO: PRIMUM NON NOCERE. FOR YOUR RECORDS: WAVELIGHT EX-500 OPTICAL ZONE TREATED: 6.7 MM ON BOTH EYES.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5064222
    [1] => 25339156
    [2] => D
    [3] => 1
    [4] => I HAD LASIK EYE SURGERY IN 2010 AND HAVE EXPERIENCED WORSENING CONDITIONS; DRY EYE, BLURRED VISION.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5064292
    [1] => 25270358
    [2] => D
    [3] => 1
    [4] => A CLINICAL DIRECTOR REPORTED A PATIENT WITH AN OVERCORRECTION OF ONE DIOPTER POST LASIK TREATMENT. THE REPORTER INDICATES THE DEFAULT SETTING FOR THE VERTEX DISTANCE IS SET AND IT DID NOT CHANGE AFTER BEING ALTERED FOR A PREVIOUS PATIENT.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5064683
    [1] => 25289912
    [2] => D
    [3] => 1
    [4] => A SURGICAL TECHNICIAN REPORTED THAT WITHIN THE PAST SIX MONTHS, THE SURGEONS HAVE OPTED NOT TO USE THE LASER DUE TO "IT CAUSES MORE DLK." THIS WAS REPORTED TO THE COMPANY ENGINEER DURING A PREVENTATIVE MAINTENANCE ONSITE VISIT. IN A FOLLOW UP, THE TECHNICIAN REPORTED THAT THE SURGEONS PREFER TO USE ANOTHER, UNKNOWN EXCIMER LASER AT THEIR SITE. ADDITIONALLY, THE TECHNICIAN WAS UNABLE TO PROVIDE THE TOTAL NUMBER OF PATIENTS, PATIENT IDENTIFIERS, OR ANY FURTHER INFORMATION.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5065198
    [1] => 25312250
    [2] => D
    [3] => 1
    [4] => AN OPTOMETRIST REPORTED THAT APPROXIMATELY THREE WEEKS FOLLOWING BILATERAL LASIK SURGERY, THE PATIENT WAS DIAGNOSED WITH MEDICAMENTOSA IN BOTH EYES. THE DIAGNOSIS WAS CAUSED BY THE USE OF ARTIFICIAL TEARS WITH PRESERVATIVES. THE PATIENT REPORTED EYE DRYNESS AND IRRITATION. THE EVENT WAS TREATED WITH INCREASED TOPICAL STEROID DROPS. THE EVENT RESOLVED EIGHT WEEKS LATER. NO FURTHER INFORMATION IS EXPECTED. THERE ARE TWO RELATED REPORTS FOR THIS PATIENT. THIS REPORT ADDRESSES THE PATIENT'S LEFT EYE, AND ANOTHER MANUFACTURER REPORT WILL BE FILED FOR THE FELLOW EYE.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5065696
    [1] => 25333208
    [2] => D
    [3] => 1
    [4] => AN OPTOMETRIST REPORTED THAT ONE MONTH FOLLOWING BILATERAL LASIK, THE PATIENT WAS DIAGNOSED WITH ANTERIOR UVEITIS IS BOTH EYES. THE PATIENT REPORTED EXPERIENCING TRANSIENT LIGHT SENSITIVITY (TLSS). THE TOPICAL STEROID DROPS WERE INCREASED TO TREAT THE EVENT. THE EVENT RESOLVED WITH THE TREATMENT, THREE WEEKS LATER. NO FURTHER INFORMATION IS EXPECTED. THERE ARE TWO MEDICAL DEVICE REPORTS ASSOCIATED WITH THIS EVENT. THIS REPORT IS FOR THE LEFT EYE.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5065744
    [1] => 25336913
    [2] => D
    [3] => 1
    [4] => AN OPTOMETRIST REPORTED THAT ONE MONTH FOLLOWING BILATERAL LASIK, THE PATIENT WAS DIAGNOSED WITH ANTERIOR UVEITIS IS BOTH EYES. THE PATIENT REPORTED EXPERIENCING TRANSIENT LIGHT SENSITIVITY (TLSS). THE TOPICAL STEROID DROPS WERE INCREASED TO TREAT THE EVENT. THE EVENT RESOLVED WITH THE TREATMENT, THREE WEEKS LATER. NO FURTHER INFORMATION IS EXPECTED. THERE ARE TWO MEDICAL DEVICE REPORTS ASSOCIATED WITH THIS EVENT. THIS REPORT IS FOR THE RIGHT EYE.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5065990
    [1] => 25332089
    [2] => D
    [3] => 1
    [4] => AN OPTOMETRIST REPORTED A CASE OF CORNEAL EROSION, OBSERVED IN PATIENT'S LEFT EYE AT FOUR MONTHS POST LASIK TREATMENT. REPORTER INDICATED UPON EXAMINATION LEFT EYE WAS RED AND SWOLLEN. PATIENT NOTED LIGHT SENSITIVITY AND FOREIGN BODY SENSATION. REPORTER INDICATED THE PATIENT WAS PLACED ON AN INCREASED TOPICAL STEROID EYE DROP DOSAGE. UPON ADDITIONAL FOLLOW UP, THE SURGEON NOTED THE SYMPTOMS WERE RELATED TO SLOW HEALING AND NOT THE EXCIMER LASER. REPORTER INDICATED PATIENT SYMPTOMS RESOLVED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5066572
    [1] => 25336708
    [2] => D
    [3] => 1
    [4] => A SURGEON REPORTED THAT DURING A PHOTO REFRACTIVE KERATECTOMY (PRK) PROCEDURE OF AN UNKNOWN EYE, THE LASER SYSTEM STOPPED. THE REPORTER INDICATED THEY WERE UNABLE TO COMPLETE THE PROCEDURE DUE TO TREATMENT INFORMATION WAS NOT AVAILABLE IN LOGFILE. THE SURGEON DECIDED TO HAVE THE PATIENT RETURN IN THREE MONTHS FOR ANOTHER PROCEDURE. ADDITIONAL INFORMATION HAS BEEN REQUESTED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5067025
    [1] => 25348059
    [2] => D
    [3] => 1
    [4] => AN OPTOMETRIST REPORTED BLURRED VISION IN A PATIENT'S LEFT EYE 2 MONTHS 7 DAYS AFTER PHOTO REFRACTIVE KERATECTOMY (PRK). UPON FOLLOW UP, THE REPORTER INDICATED THE PATIENT'S PROGRESS WILL CONTINUE TO BE MONITORED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5067270
    [1] => 25364285
    [2] => D
    [3] => 1
    [4] => A HEALTHCARE PROFESSIONAL REPORTED THAT TREATMENT RESULTS WERE NOT CORRECT. THE ISSUE APPEARED AFTER REFRACTIVE SURGERIES, OFTEN A DAY OR MORE AFTER TREATMENT. THERE WAS NO PATIENT IMPACT AND THE NUMBER OF PATIENTS WAS UNKNOWN. ADDITIONAL INFORMATION HAS BEEN REQUESTED BUT NOT RECEIVED TO DATE.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5069462
    [1] => 25480410
    [2] => D
    [3] => 1
    [4] => THE CLINIC REPORTED THAT A LASER VISION CORRECTION PATIENT PRESENTED WITH EPITHELIAL INGROWTH AFFECTING VISUAL ACUITY IN RIGHT EYE AT THE ONE MONTH POST ENHANCEMENT TREATMENT. IT WAS STATED THAT THE PATIENT HAD NO LOSS OF BEST CORRECTED VISUAL ACUITY (BCVA). THE PATIENT COMPLAINED OF BLURRED NEAR VISION IN RIGHT EYE (NEAR EYE, MONOVISION). PATIENT REPORTED SYMPTOMS ARE NOT INTERFERING WITH DAILY ACTIVITIES. A FLAP LIFT AND RINSE WAS PERFORMED AND PATIENT'S SYMPTOMS RESOLVED ON (B)(6) 2015. BCVA FROM (B)(6) 2009: RIGHT EYE PRE-OP 20/20 -4.75 X -.75 X 135; LEFT EYE PRE-OP 20/20 -5.00 X -.75 X 16.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5069605
    [1] => 25479883
    [2] => D
    [3] => 1
    [4] => THE CLINIC REPORTED THAT A LASER VISION CORRECTION PATIENT PRESENTED WITH ANTERIOR UVEITIS AT 1 MONTHS POST TREATMENT. ORIGINAL TREATMENT DONE ON (B)(6) 2015. THE TOPICAL STEROID DOSAGE WAS INCREASED. IT WAS STATED THAT THE PATIENT HAD NO LOSS OF BEST CORRECTED VISUAL ACUITY (BCVA). THE PATIENT COMPLAINED OF TRANSIENT LIGHT SENSITIVITY SYNDROME (LIGHT SENSITIVITY). PATIENT REPORTED SYMPTOMS ARE NOT INTERFERING WITH DAILY ACTIVITIES. PATIENT'S SYMPTOMS RESOLVED ON (B)(6) 2015. BCVA FROM (B)(6) 2015: RIGHT EYE PRE-OP 20/20 -2.75 X -.75 X 107; LEFT EYE PRE-OP 20/20 -2.50 X -1.00 X 66. BCVA FROM (B)(6) 2015 RIGHT EYE POST-OP 20/20 .00 X .00 X 90; LEFT EYE POST-OP 20/20 .00 X .00 X 90.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5069809
    [1] => 25480226
    [2] => D
    [3] => 1
    [4] => AN OPTOMETRIST REPORTED THAT APPROXIMATELY THREE WEEKS FOLLOWING BILATERAL LASIK SURGERY, THE PATIENT WAS DIAGNOSED WITH MEDICAMENTOSA IN BOTH EYES. THE DIAGNOSIS WAS CAUSED BY THE USE OF ARTIFICIAL TEARS WITH PRESERVATIVES. THE PATIENT REPORTED EYE DRYNESS AND IRRITATION. THE EVENT WAS TREATED WITH INCREASED TOPICAL STEROID DROPS. THE EVENT RESOLVED EIGHT WEEKS LATER. NO FURTHER INFORMATION IS EXPECTED. THERE ARE TWO RELATED REPORTS FOR THIS PATIENT. THIS REPORT ADDRESSES THE PATIENT'S RIGHT EYE, AND ANOTHER MANUFACTURER REPORT WILL BE FILED FOR THE FELLOW EYE.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5070868
    [1] => 25561150
    [2] => D
    [3] => 1
    [4] => AN OPTOMETRIST REPORTED THAT A PATIENT WAS NOTED TO HAVE TISSUE EROSION IN THE RIGHT EYE APPROXIMATELY TWO WEEKS POST PHOTOREFRACTIVE KERATECTOMY. A BANDAGE CONTACT LENS WAS PLACED ON THE EYE. THE PATIENT EXPERIENCED PAIN WITH DECREASED VISION IN THE RIGHT EYE TWO DAYS AFTER THE BANDAGE CONTACT LENS WAS REMOVED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5072180
    [1] => 25614976
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED SUCTION LOSS OCCURRED DURING PROCEDURE WHILE LASER FIRING WITH AN INTRALASE PATIENT INTERFACE (PI). THE SURGERY WAS DELAYED FOR 30 MINUTES AND INTRALASE WAS USED TO CREATE FLAP AGAIN. NO PATIENT INJURY AND/OR COMPLICATIONS WERE REPORTED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5072401
    [1] => 25611881
    [2] => D
    [3] => 1
    [4] => THE CLINIC REPORTED THAT A LASER VISION CORRECTION PATIENT PRESENTED WITH IRREGULAR EPITHELIUM IN BOTH EYES -MAP/DOT/FINGERPRINT ORIENTATION AT 1 MONTH POST LASIK TREATMENT. IT WAS STATED THAT THE PATIENT HAD LOSS OF BEST CORRECTED VISUAL ACUITY (BCVA). THE PATIENT COMPLAINED OF BLURRY VISION AND DOUBLE VISION ABOUT 3 WEEKS POST TREATMENT. PATIENT WAS NOT ABLE TO PASS THE DRIVING TEST AT THE (B)(6). PATIENT REPORTED SYMPTOMS ARE WERE INTERFERING WITH DAILY ACTIVITIES AS SHE WAS UNABLE TO DRIVE. PATIENT REQUESTED A WORK NOTE TO EXCUSE FROM DRIVING UNTIL NEXT APPOINTMENT. PATIENT WAS SCHEDULED TO SEE SURGEON FOR TREATMENT OPTIONS AND EPITHELIAL DEBRIDEMENT WAS REQUIRED. SANS CORRECTED VISUAL ACUITY (SCVA): RIGHT EYE 20/30; LEFT EYE 20/40. BCVA FROM (B)(6) 2015: RIGHT EYE PRE-OP 20/20 -1.25 X -.50 X 158; LEFT EYE PRE-OP 20/20 -1.25 X -.25 X 135. BCVA FROM (B)(6) 2015: RIGHT EYE POST-OP 20/30; LEFT EYE POST-OP 20/25.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5073114
    [1] => 25612838
    [2] => D
    [3] => 1
    [4] => THE CLINIC REPORTED THAT A LASER VISION CORRECTION PATIENT PRESENTED WITH EPITHELIAL INGROWTH IN RIGHT EYE AT 5 MONTHS POST TREATMENT. A FLAP LIFT AND RINSE WAS PERFORMED AND ANTIBIOTICS WERE GIVEN. IT WAS STATED THAT THE PATIENT HAD NO LOSS OF BEST CORRECTED VISUAL ACUITY (BCVA). THE PATIENT HAD NO COMPLAINTS. PATIENT REPORTED SYMPTOMS ARE NOT INTERFERING WITH DAILY ACTIVITIES. A SEPARATE REPORT IS BEING SUBMITTED FOR A SECOND DEVICE, EXCIMER LASER SERIAL NUMBER (B)(4). BCVA FROM (B)(6) 2014: RIGHT EYE PRE-OP 20/20 -1.25 X -1.25 X 105, LEFT EYE PRE-OP 20/20 -2.25 X -1.00 X 80. BCVA FROM (B)(6) 2015: RIGHT EYE POST-OP 20/20 .00 X -.50 X 155, LEFT EYE POST-OP 20/20 .25 X -.25 X 5.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5073127
    [1] => 25612986
    [2] => D
    [3] => 1
    [4] => THE CLINIC REPORTED THAT A LASER VISION CORRECTION PATIENT PRESENTED WITH EPITHELIAL INGROWTH IN RIGHT EYE AT 5 MONTHS POST TREATMENT. A FLAP LIFT AND RINSE WAS PERFORMED AND ANTIBIOTICS WERE GIVEN. IT WAS STATED THAT THE PATIENT HAD NO LOSS OF BEST CORRECTED VISUAL ACUITY (BCVA). THE PATIENT HAD NO COMPLAINTS. PATIENT REPORTED SYMPTOMS ARE NOT INTERFERING WITH DAILY ACTIVITIES. A SEPARATE REPORT(MFR REPORT NUMBER 3006695864-2015-00594) WAS SUBMITTED FOR A SECOND DEVICE, FEMTOSECOND LASER 1007-40404 BCVA FROM (B)(6) 2014: RIGHT EYE PRE-OP 20/20 -1.25 X -1.25 X 105; LEFT EYE PRE-OP 20/20 -2.25 X -1.00 X 80. BCVA FROM (B)(6) 2015: RIGHT EYE POST-OP 20/20 .00 X -.50 X 155; LEFT EYE POST-OP 20/20 .25 X -.25 X 5.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5073365
    [1] => 25616662
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED THEY EXPERIENCED SUCTION LOSS / INADEQUATE SEAL ON THE LEFT EYE (OS) WITH AN INTRALASE PATIENT INTERFACE (PI) AFTER THE PATIENT WAS APPLANATED. IT WAS REPORTED THAT AN ELECTRONIC PROCEDURE WAS LOST. THE DOCTOR COMPLETED THE PROCEDURE SUCCESSFULLY BY SWITCHING THE PI.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5073366
    [1] => 25616950
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED THEY EXPERIENCED SUCTION LOSS / INADEQUATE SEAL ON THE LEFT EYE (OS) WITH AN INTRALASE PATIENT INTERFACE (PI) AFTER THE PATIENT WAS APPLANATED. IT WAS REPORTED THAT AN ELECTRONIC PROCEDURE WAS LOST. THE DOCTOR COMPLETED THE PROCEDURE SUCCESSFULLY BY SWITCHING THE PI.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5073367
    [1] => 25618903
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED THEY EXPERIENCED SUCTION LOSS / INADEQUATE SEAL ON THE RIGHT EYE (OD) WITH AN INTRALASE PATIENT INTERFACE (PI) AFTER THE PATIENT WAS APPLANATED. IT WAS REPORTED THAT THE DOCTOR COMPLETED THE PROCEDURE SUCCESSFULLY BY SWITCHING THE PI.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5073368
    [1] => 25619382
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED THEY EXPERIENCED SUCTION LOSS / INADEQUATE SEAL ON THE RIGHT EYE (OD) WITH AN INTRALASE PATIENT INTERFACE (PI) AFTER THE PATIENT WAS APPLANATED. THE DOCTOR COMPLETED THE PROCEDURE SUCCESSFULLY BY SWITCHING THE PI.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5073414
    [1] => 25612396
    [2] => D
    [3] => 1
    [4] => ACCOUNT REPORTED PATIENT HAD FLAP CREATION CUSTOMVUE PROCEDURE (-1.34 - 0.74 X 110) WITH ACTIVE TRACK AND IRIS REGISTRATION ENABLED IN (B)(6) 2015 AND DURING (B)(6) 2015 POST OP VISIT IT WAS NOTICED HE HAD UNEXPECTED REFRACTIVE OUTCOME IN HIS RIGHT EYE . DURING (B)(6) 2015 VISIT SURGEON NOTICED VERY FLAP DEPRESSION ON THE SUPERIOR AXIAL CURVE. PATIENT RIGHT EYE POST OP +7.50 - 5.50 X 093 , 20/20 OD BEST CORRECTED VISUAL ACUITY (UNCORRECTED VISUAL ACUITY - UCVA 20/60-). NO ISSUES WITH LEFT EYE AS IT WAS 20/15 POST OP. SURGEON HAS REASON TO BELIEVE THAT A LENTICULE WAS SOMEHOW ABLATED IN THE SUPERIOR HALF OF HIS CORNEA HOWEVER, HE IS UNSURE IF THE REFRACTIVE RESULT IS FROM THE LASIK FLAP OR FROM THE STROMAL BED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5073415
    [1] => 25613354
    [2] => D
    [3] => 1
    [4] => PATIENT TREATMENT WAS DONE IN (B)(6) 2015. SURGEON REPORTED THAT DURING IFS FLAP CREATION SHE LOST SUCTION MID RASTER (WHILE LASER WAS FIRING) IN RIGHT EYE. SURGEON REPOSITIONED THE SAME CONE, AND CUT A WHOLE NEW FLAP 30 MICRONS DEEPER. PATIENT PRESENTED DURING POST OP TREATMENT WITH SIGNIFICANT EPITHELIAL DEFECT AND STROMAL INFLAMMATION. SURGEON ELECTED TO RE-LIFT THE FLAP AT POST OP DAY #2 TO IRRIGATE AND REPOSITION DUE TO 2+ DIFFUSE LAMELLAR KERATITIS (DLK). PATIENT WAS GIVEN ORAL AND TOPICAL STEROIDS AND FOLLOWED FOR SEVERAL WEEKS TO WAIT FOR FLAP EDEMA TO SETTLE DOWN. PATIENT WAS SEEN IN (B)(6) 2015 AND PATIENT RIGHT EYE POST OP +7.50 - 5.50 X 093 = 20/20 OD (UNCORRECTED VISUAL ACUITY - UCVA 20/60-). NO ISSUES WITH LEFT EYE AS IT WAS 20/15 POST OP. SURGEON HAS REASON TO BELIEVE THAT A LENTICULE WAS SOMEHOW ABLATED IN THE SUPERIOR HALF OF HIS CORNEA HOWEVER, HE IS UNSURE IF THE REFRACTIVE RESULT IS FROM THE LASIK FLAP OR FROM THE STROMAL BED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5073662
    [1] => 26169262
    [2] => D
    [3] => 1
    [4] => A DOCTOR OF OPHTHALMOLOGY REPORTED AN EYE TRACKER ISSUE OCCURRED IN TRACKING COLORED EYES IN AUTOMATIC MODE ESPECIALLY. THE SURGEON NEED TO ADJUST THE EYE TRACKER MANUALLY. THE USER ADJUSTED THE EYE TRACKER ILLUMINATION NOT CORRECTLY. ADDITIONAL INFORMATION HAS BEEN REQUESTED BUT NOT RECEIVED TO DATE.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5074969
    [1] => 25716127
    [2] => D
    [3] => 1
    [4] => MICROKERATOME CUSTOM LASIK IN (B)(6) 2014. NO EGREGIOUS NEGLIGENCE INTRA-OP (CERTAIN NEGLIGENCE PREOP: MISSED DIAGNOSIS OF ROSACEA). INFORMED CONSENT PRACTICES UNETHICAL, BILATERAL TREATMENT (BOTH EYES) PREVENTS ABILITY TO PROVIDE TRUE INFORMED CONSENT. LASIK, MICROKERATOMES AND EXCIMER LASERS ARE FLAWED TO BEGIN WITH BUT AT THE BARE MINIMUM NEED TO BE LABELLED AS THE HIGH RISK DEVICES FOR WHICH THEY ARE. ON TO THE ADVERSE EVENTS. FOLLOWING LASIK, I EXPERIENCE UNREMITTING DRY EYES AND PAIN IN GENERAL. SO MUCH THAT I CANNOT GO ABOUT MY DAILY TASKS BECAUSE MY EYES ARE ALWAYS HURTING AND LOOK THE PART TOO (BLOODSHOT, GLAZED). MY NIGHT-VISION (LOW LIGHT CONDITIONS, DRIVING) HAS BEEN SEVERELY HINDERED AND COMPROMISED. THE CORNEAL FLAP CREATED IN LASIK NEVER HEALS AND NOW THAT IS ANOTHER ADVERSE EVENT REPORT JUST WAITING TO HAPPEN. MY VISION IS NOW FILLED WITH FLOATERS AS A RESULT OF THE INVASIVENESS OF THE PROCEDURE AND I AM LOOKING AT A VITRECTOMY AND CATARACT SURGERY IN THE FUTURE, NOT TO MENTION AN OVERALL WEAKENED EYE IN TERMS OF ITS HEALTH AND BIOMECHANICAL STRENGTH. BE THESE THINGS AS THEY MAY, JUST DIRECTLY INFORM THE PUBLIC OF THEM. I CAN HONESTLY SAY THAT I WAS BARELY AWARE OF THE FREQUENCY AND SEVERITY OF THE COMPLICATIONS OF LASIK. THIS LACK OF INFO AND MISINFORMATION IS PURPOSELY CRAFTED BY THESE CLINICS WHO CARE NOT ONE OUNCE FOR PTS WHOSE EYES AND LIVES THEY DESTROY. THE FDA AND IT'S LAX REGULATIONS ARE INEFFECTIVE AND INSUFFICIENT IN COMBATING THE FALSE ADVERTISING AND PUBLIC PERCEPTION OF LASER CORRECTION. I URGE YOU, BY ALL THAT IS GOOD IN THE WORLD, FROM EVERY FIBRE OF MY BEING AND OF THE OTHERS INJURED BY LASIK, TO ISSUE A PUBLIC HEALTH ADVISORY AND/OR BLACK BOX WARNING LIKE SO MANY BEFORE WE HAVE ASKED OF YOU. I HAD TO LEAVE MY JOB BECAUSE MY EYES HURT ALL THE TIME AND I CAN NO LONGER LOOK AT A COMPUTER SCREEN WHILE MAINTAINING CUSTOMER SERVICE AND MY OTHER JOB RESPONSIBILITIES ((B)(6)). MY SOCIAL LIFE HAS COMPLETELY ERODED AND MY PERSONAL PROSPECTS HAVE BEEN LOST. IF I DID NOT HAVE THE SUPPORT OF MY FAMILY, THERE WOULD BE NOTHING TO PREVENT ME FROM FALLING INTO A DEEPER DEPRESSION THAN I ALREADY AM. SUICIDAL IDEATION IS SOMETHING THAT I AM NOW ALL TOO FAMILIAR WITH. MY LIFE HAS COMPLETELY DETERIORATED BECAUSE MY EYES HAVE BEEN SEVERELY DAMAGED BY A UNNECESSARY AND VERY MUCH CORRUPT PROCEDURE AND INDUSTRY. AND MY LIFE WAS GOOD. I WAS HAPPY. I DID NOT ASK FOR THIS, NOR WAS I EVEN AWARE THAT IT COULD ACTUALLY HAPPEN. LASIK HAS BEEN THE WORST DECISION OF MY LIFE AND I REGRET IT EVERY DAY AND SURELY WILL CONTINUE TO REGRET UNTIL THE DAY I DIE. I AM (B)(6) AS OF THIS WRITING AND BY THE WAY, THE CLINIC CONSIDERS ME A SUCCESS BECAUSE I CAN ROUGHLY ACHIEVE 20/20 ACUITY, OTHER COMPLICATIONS BE DAMNED. I WAS 20/20 WITH MY GLASSES OF COURSE SO BENEFIT HAS HARDLY BEEN WORTH THE RISK. THE FDA HELD A LASIK PANEL IN APRIL 2008 WHERE NUMEROUS PEOPLE, PTS AND PROFESSIONALS ALIKE, TOLD YOU EVERYTHING YOU NEEDED TO KNOW ABOUT LASIK. SEVEN YEARS LATER AND NOTHING HAS CHANGED. IF YOU WERE TO HOST A SIMILAR FORUM TODAY, THE TESTIMONIES WOULD BE THE SAME, ONLY IN GREATER NUMBER AND IN GREATER DETAIL. YOU CONDUCTED A QUALITY OF LIFE SURVEY WITH RESULTS PUBLISHED IN OCTOBER 2014 WHERE "DISABLING SYMPTOMS WERE FOUND IN A SIGNIFICANT NUMBERS OF PTS". HOW MANY EYES AND LIVES MUST BE DESTROYED BEFORE YOU DO WHAT IS RIGHT AND ALERT THE PUBLIC AND BLACK BOX THIS PRODUCT? THESE OPHTHALMOLOGISTS ARE NOT ETHICAL. THEY HAVE LONG DEPARTED THE PATH OF MEDICINE AND HEALING IN SEARCH OF FINANCIAL GAIN AND EGO. AND THIS IS THE ROOT OF THE PROBLEM. PROFIT OVER PT WELFARE VIA INDIFFERENT LASER SURGEONS. YOU COULD BE AN IDEAL CANDIDATE, A POOR CANDIDATE, IT MAKES NO DIFFERENCE. THEY WANT YOU UNDER THE LASER, OUT THE OTHER SIDE SO THEY GET RICH AND AN INNOCENT PERSON IS NEEDLESSLY COMPROMISED. THE STAKES ARE TOO HIGH. OUR PRECIOUS EYES, PLEASE DO SOMETHING!.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5075166
    [1] => 25702701
    [2] => D
    [3] => 1
    [4] => A PARALEGAL REPORTED THAT FOLLOWING LASIK SURGERY, THE PATIENT PRESENTED WITH DIFFUSED LAMELLAR KERATITIS IN BOTH EYES. ADDITIONAL INFORMATION WAS REQUESTED REGARDING THE RESOLUTION OF THE EVENT. THERE ARE TWO MEDICAL DEVICE REPORTS ASSOCIATED WITH THIS EVENT. THIS REPORT IS FOR THE RIGHT EYE.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5075369
    [1] => 25714351
    [2] => D
    [3] => 1
    [4] => A PARALEGAL REPORTED THAT FOLLOWING LASIK SURGERY, THE PATIENT PRESENTED WITH DIFFUSED LAMELLAR KERATITIS IN BOTH EYES. ADDITIONAL INFORMATION WAS REQUESTED REGARDING THE RESOLUTION OF THE EVENT. THERE ARE TWO MEDICAL DEVICE REPORTS ASSOCIATED WITH THIS EVENT. THIS REPORT IS FOR THE LEFT EYE.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5075414
    [1] => 25714879
    [2] => D
    [3] => 1
    [4] => A PARALEGAL REPORTED THAT FOLLOWING LASIK SURGERY, THE PATIENT PRESENTED WITH DIFFUSED LAMELLAR KERATITIS IN BOTH EYES. ADDITIONAL INFORMATION WAS REQUESTED REGARDING THE RESOLUTION OF THE EVENT. THERE ARE TWO MEDICAL DEVICE REPORTS ASSOCIATED WITH THIS EVENT. THIS REPORT IS FOR THE RIGHT EYE.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5075419
    [1] => 25716267
    [2] => D
    [3] => 1
    [4] => A PARALEGAL REPORTED THAT FOLLOWING LASIK SURGERY, THE PATIENT PRESENTED WITH DIFFUSED LAMELLAR KERATITIS IN BOTH EYES. ADDITIONAL INFORMATION WAS REQUESTED REGARDING THE RESOLUTION OF THE EVENT. THERE ARE TWO MEDICAL DEVICE REPORTS ASSOCIATED WITH THIS EVENT. THIS REPORT IS FOR THE LEFT EYE.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5075439
    [1] => 25716229
    [2] => D
    [3] => 1
    [4] => A PARALEGAL REPORTED THAT FOLLOWING LASIK SURGERY, THE PATIENT PRESENTED WITH DIFFUSED LAMELLAR KERATITIS IN BOTH EYES. ADDITIONAL INFORMATION WAS REQUESTED REGARDING THE RESOLUTION OF THE EVENT. THERE ARE TWO MEDICAL DEVICE REPORTS ASSOCIATED WITH THIS EVENT. THIS REPORT IS FOR THE RIGHT EYE.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5075664
    [1] => 32515331
    [2] => D
    [3] => 1
    [4] => NO ADDITIONAL INFORMATION HAS BEEN RECEIVED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5075666
    [1] => 32523140
    [2] => D
    [3] => 1
    [4] => NO ADDITIONAL INFORMATION HAS BEEN RECEIVED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5075721
    [1] => 32556071
    [2] => D
    [3] => 1
    [4] => NO ADDITIONAL INFORMATION HAS BEEN RECEIVED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5076031
    [1] => 32556304
    [2] => D
    [3] => 1
    [4] => NO ADDITIONAL INFORMATION HAS BEEN RECEIVED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5076032
    [1] => 32557674
    [2] => D
    [3] => 1
    [4] => NO ADDITIONAL INFORMATION HAS BEEN RECEIVED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5076114
    [1] => 32548123
    [2] => D
    [3] => 1
    [4] => NO ADDITIONAL INFORMATION HAS BEEN RECEIVED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5076115
    [1] => 32552028
    [2] => D
    [3] => 1
    [4] => NO ADDITIONAL INFORMATION HAS BEEN RECEIVED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5076127
    [1] => 32552076
    [2] => D
    [3] => 1
    [4] => NO ADDITIONAL INFORMATION HAS BEEN RECEIVED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5076130
    [1] => 32555775
    [2] => D
    [3] => 1
    [4] => NO ADDITIONAL INFORMATION HAS BEEN RECEIVED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5076418
    [1] => 26135735
    [2] => D
    [3] => 1
    [4] => IT WAS REPORTED THAT DURING PROCEDURE SUCTION LOSS WHILE LASER FIRING OCCURRED WITH AN INTRALASE PATIENT INTERFACE (PI). THERE IS NO PATIENT INJURY REPORTED AND NO PATIENT COMPLICATIONS.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5077325
    [1] => 26234023
    [2] => D
    [3] => 1
    [4] => AN OPHTHALMIC SURGEON REPORTED THAT THERE WAS A MOVEMENT ISSUE WITH THE BED DURING A SURGERY. THERE WAS NO PATIENT IMPACT. ADDITIONAL INFORMATION HAS BEEN REQUESTED BUT NOT RECEIVED TO DATE. THIS IS THE FIRST OF TWO REPORTS BEING FILED FOR THIS EVENT. THIS REPORT IS FOR THE SECOND PATIENT.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5079062
    [1] => 25878113
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED THEY EXPERIENCED SUCTION LOSS DURING SURGERY ON THE RIGHT EYE (OD) WITH AN INTRALASE PATIENT INTERFACE (PI) AFTER THE PATIENT WAS APPLANATED. IT WAS REPORTED THAT THE PATIENT SQUEEZED EYE AND THAT AN ELECTRONIC PROCEDURE WAS LOST. THE DOCTOR COMPLETED THE PROCEDURE SUCCESSFULLY BY SWITCHING OUT THE PI.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5079539
    [1] => 25876167
    [2] => D
    [3] => 1
    [4] => SURGEON REPORTED THAT SYSTEM COMPLETED INLAY CHANNEL. FOLLOWING CREATION OF THE INLAY CHANNEL SURGEON WAS UNABLE TO COMPLETE THE DISSECTION OF THE CHANNEL AND THEREFORE ABORTED THE COMPLETION OF THE KAMRA INLAY. PATIENT SCHEDULE TO RETURN AT 1 MONTH TO REPEAT THE CHANNEL PROCEDURE. PATIENT 1 DAY POST OP UNCORRECTED VISUAL ACUITY (UCVA) WAS 20/50, NO MANIFEST REFRACTION COMPLETED. PATIENT UCVA PREOP WAS 20/25, AND CYCLOPLEGIC REFRACTION WAS -0.75 +0.50 X173, BEST CORRECTED VISUAL ACUITY (BCVA) 20/20.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5079768
    [1] => 25877997
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED THEY EXPERIENCED SUCTION LOSS DURING SURGERY ON THE RIGHT EYE (OD) WITH AN INTRALASE PATIENT INTERFACE (PI) AFTER THE PATIENT WAS APPLANATED. IT WAS REPORTED THAT THE PATIENT SQUEEZED EYE AND THAT AN ELECTRONIC PROCEDURE WAS LOST. THE DOCTOR COMPLETED THE PROCEDURE SUCCESSFULLY BY SWITCHING OUT THE PI.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5080903
    [1] => 25953609
    [2] => D
    [3] => 1
    [4] => A PARALEGAL REPORTED THAT FOLLOWING LASIK SURGERY, THE PATIENT PRESENTED WITH DIFFUSED LAMELLAR KERATITIS IN BOTH EYES. ADDITIONAL INFORMATION WAS REQUESTED REGARDING THE RESOLUTION OF THE EVENT. THERE ARE TWO MEDICAL DEVICE REPORTS ASSOCIATED WITH THIS EVENT. THIS REPORT IS FOR THE LEFT EYE.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5081704
    [1] => 25995190
    [2] => D
    [3] => 1
    [4] => IT WAS REPORTED THAT DURING PROCEDURE SUCTION LOSS WHILE LASER FIRING OCCURRED WITH AN INTRALASE PATIENT INTERFACE (PI). THERE IS NO PATIENT INJURY REPORTED AND NO PATIENT COMPLICATIONS.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5081788
    [1] => 25994886
    [2] => D
    [3] => 1
    [4] => IT WAS REPORTED THAT DURING PROCEDURE SUCTION LOSS WHILE LASER FIRING OCCURRED WITH AN INTRALASE PATIENT INTERFACE (PI). THERE IS NO PATIENT INJURY REPORTED AND NO PATIENT COMPLICATIONS.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5082206
    [1] => 25994453
    [2] => D
    [3] => 1
    [4] => IT WAS REPORTED THAT DURING PROCEDURE SUCTION LOSS WHILE LASER FIRING OCCURRED WITH AN INTRALASE PATIENT INTERFACE (PI). THERE IS NO PATIENT INJURY REPORTED AND NO PATIENT COMPLICATIONS.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5082412
    [1] => 25994936
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED SUCTION LOSS DURING SURGERY-SUCTION RING ASSEMBLY ISSUE WITH AN INTRALASE PATIENT INTERFACE (PI) AFTER THE PATIENT WAS APPLANATED AND AFTER THE LASER FIRED. DESCRIPTION OF THE PROBLEM: DEFECTIVE SUCTION RING. LOSS OF SUCTION DURING RASTER PATTERN. IT IS ALSO NOTED THAT THE PROCEDURE WAS COMPLETED SUCCESSFULLY. THERE WAS NO PATIENT INJURY REPORTED AND NO SURGICAL INTERVENTION WAS REQUIRED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5082491
    [1] => 25994710
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED SUCTION LOSS DURING SURGERY-SUCTION RING ASSEMBLY ISSUE WITH AN INTRALASE PATIENT INTERFACE (PI) AFTER THE PATIENT WAS APPLANATED AND AFTER THE LASER FIRED. DESCRIPTION OF THE PROBLEM: DEFECTIVE SUCTION RING. LOSS OF SUCTION DURING RASTER PATTERN. IT IS ALSO NOTED THAT THE PROCEDURE WAS COMPLETED SUCCESSFULLY. THERE WAS NO PATIENT INJURY REPORTED AND NO SURGICAL INTERVENTION WAS REQUIRED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5082554
    [1] => 25995124
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED SUCTION LOSS DURING RASTER PATTERN-SUCTION RING ASSEMBLY ISSUE WITH AN INTRALASE PATIENT INTERFACE (PI) AFTER THE PATIENT WAS APPLANATED AND AFTER THE LASER FIRED. IT WAS REPORTED THAT ONE PROCEDURE WAS LOST. IT WAS ALSO NOTED THAT THE PROCEDURE WAS COMPLETED SUCCESSFULLY. THERE WAS NO PATIENT INJURY REPORTED AND NO SURGICAL INTERVENTION WAS REQUIRED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5082665
    [1] => 25992911
    [2] => D
    [3] => 1
    [4] => AN OPTOMETRIST REPORTED A BILATERAL CASE OF CORNEAL HAZE, OBSERVED AT NINE WEEKS POST PHOTO REFRACTIVE KERATECTOMY (PRK) TREATMENT. REPORTER INDICATED TOPICAL STEROID EYE DROP DOSAGE WAS INCREASED. ATTEMPTS HAVE BEEN MADE TO OBTAIN ADDITIONAL PATIENT INFORMATION, AT THIS TIME NO ADDITIONAL INFORMATION HAS BEEN RECEIVED. THERE ARE TWO RELATED REPORTS FOR THIS PATIENT. THIS REPORT ADDRESSES THE PATIENT'S LEFT EYE, AND ANOTHER MANUFACTURER REPORT WILL BE FILED FOR THE FELLOW EYE.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5082937
    [1] => 25994634
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED SUCTION LOSS DURING SURGERY-SUCTION RING ASSEMBLY ISSUE WITH AN INTRALASE PATIENT INTERFACE (PI) AFTER THE PATIENT WAS APPLANATED AND AFTER THE LASER FIRED. IT IS ALSO NOTED THAT THE PROCEDURE WAS COMPLETED SUCCESSFULLY. THERE WAS NO PATIENT INJURY REPORTED AND NO SURGICAL INTERVENTION WAS REQUIRED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5082944
    [1] => 25995364
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED SUCTION LOSS DURING RASTER PATTERN-SUCTION RING ASSEMBLY ISSUE WITH AN INTRALASE PATIENT INTERFACE (PI) AFTER THE PATIENT WAS APPLANATED AND AFTER THE LASER FIRED. IT WAS REPORTED THAT TWO PROCEDURES WERE LOST. IT WAS ALSO NOTED THAT THE PROCEDURE WAS COMPLETED SUCCESSFULLY. THERE WAS NO PATIENT INJURY REPORTED AND NO SURGICAL INTERVENTION WAS REQUIRED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5083137
    [1] => 25994961
    [2] => D
    [3] => 1
    [4] => THE ACCOUNT REPORTED SUCTION LOSS DURING RASTER PATTERN-SUCTION RING ASSEMBLY ISSUE WITH AN INTRALASE PATIENT INTERFACE (PI) AFTER THE PATIENT WAS APPLANATED AND AFTER THE LASER FIRED. IT WAS REPORTED THAT TWO PROCEDURES WERE LOST. IT WAS ALSO NOTED THAT THE PROCEDURE WAS COMPLETED SUCCESSFULLY. THERE WAS NO PATIENT INJURY REPORTED AND NO SURGICAL INTERVENTION WAS REQUIRED.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5083269
    [1] => 25988470
    [2] => D
    [3] => 1
    [4] => THE CLINIC REPORTED THAT A LASER VISION CORRECTION PATIENT PRESENTED WITH FLAP STRIAE ON BOTH EYES ONE DAY POST TREATMENT. IT WAS STATED THAT THE PATIENT HAD NO LOSS OF BEST CORRECTED VISUAL ACUITY (BCVA). THE PATIENT COMPLAINED OF BLURRY VISION. PATIENT HAD FLAP LIFT AND RINSE. BCVA FROM (B)(6) 2015: RIGHT EYE PRE-OP 20/20 -2.50 X -1.00 X 2. LEFT EYE PRE-OP 20/20 -2.00 X -1.00 X 16.

)
contents of $vec object(Ds\Vector) from $fileIterator:
Ds\Vector Object
(
    [0] => 5087187
    [1] => 26443509
    [2] => D
    [3] => 1
    [4] => A CUSTOMER REPORTED LOW ENERGY AND HIGH VOLTAGE DURING LASIK TREATMENT. UPON ADDITIONAL FOLLOW UP IT WAS REPORTED THAT THE PATIENT INVOLVED IS DOING WELL WITHOUT FURTHER ISSUES.

)
